version: "3.7"

services:
  db:
    image:  postgres
    restart: always 
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: 123456
       POSTGRES_DB: nestdb
       POSTGRES_USER: postgres
       PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes: 
  postgres_data: